// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/grigri/pv/internal/auth"
	"github.com/grigri/pv/internal/config"
	"github.com/grigri/pv/internal/infra"
	"github.com/grigri/pv/internal/service"
	"github.com/spf13/cobra"
)

// Injectors from wire.go:

func BuildCLI() (*cobra.Command, error) {
	store, err := config.NewFileStore()
	if err != nil {
		return nil, err
	}
	infraStore := infra.NewGitHubStore(store)
	gitHubClient := auth.NewGitHubClient()
	tokenValidator := auth.NewTokenValidator(gitHubClient)
	authService := service.NewAuthService(store, gitHubClient, tokenValidator)
	commands := ProvideCommands(infraStore, authService)
	command := ProvideRootCommand(commands)
	return command, nil
}

// wire.go:

// InfraSet provides infrastructure components
var InfraSet = wire.NewSet(infra.NewGitHubStore, config.NewFileStore)

// AuthSet provides authentication related components
var AuthSet = wire.NewSet(auth.NewGitHubClient, auth.NewTokenValidator, service.NewAuthService)

// CommandSet provides CLI commands
var CommandSet = wire.NewSet(
	ProvideCommands,
	ProvideRootCommand,
)
