// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/grigri/pv/internal/auth"
	"github.com/grigri/pv/internal/config"
	"github.com/grigri/pv/internal/service"
	"github.com/grigri/pv/internal/validator"
	"github.com/spf13/cobra"
)

// Injectors from wire.go:

func BuildCLI() (*cobra.Command, error) {
	store, err := config.NewFileStore()
	if err != nil {
		return nil, err
	}
	gitHubStore := ProvideGitHubStore(store)
	cacheManager, err := ProvideCacheManager()
	if err != nil {
		return nil, err
	}
	infraStore := ProvideCachedStore(gitHubStore, cacheManager, store)
	gitHubClient := auth.NewGitHubClient()
	tokenValidator := auth.NewTokenValidator(gitHubClient)
	authService := service.NewAuthService(store, gitHubClient, tokenValidator)
	yamlValidator := validator.NewYAMLValidator()
	promptService := service.NewPromptService(infraStore, yamlValidator)
	util := ProvideClipboardUtil()
	parser := ProvideVariableParser()
	tuiInterface := ProvideTUIInterface()
	commands := ProvideCommands(infraStore, store, authService, promptService, util, parser, tuiInterface)
	command := ProvideRootCommand(commands)
	return command, nil
}

// wire.go:

// InfraSet provides infrastructure components
var InfraSet = wire.NewSet(
	ProvideGitHubStore, config.NewFileStore, ProvideCacheManager,
	ProvideCachedStore,
)

// AuthSet provides authentication related components
var AuthSet = wire.NewSet(auth.NewGitHubClient, auth.NewTokenValidator, service.NewAuthService)

// ServiceSet provides service layer components
var ServiceSet = wire.NewSet(validator.NewYAMLValidator, service.NewPromptService)

// GetCommandSet provides components specific to the get command
var GetCommandSet = wire.NewSet(
	ProvideClipboardUtil,
	ProvideVariableParser,
	ProvideTUIInterface,
)

// CommandSet provides CLI commands
var CommandSet = wire.NewSet(
	ProvideCommands,
	ProvideRootCommand,
)
