// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/spf13/cobra"
	"pv/cmd"
	"pv/internal/infra"
)

// Injectors from wire.go:

func BuildCLI() (*cobra.Command, error) {
	store := infra.NewMemoryStore()
	listCmd := cmd.NewListCommand(store)
	command := cmd.NewRootCommand(listCmd)
	return command, nil
}

// wire.go:

var StoreSet = wire.NewSet(infra.NewMemoryStore, cmd.NewListCommand, cmd.NewRootCommand)
