// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/grigri201/prompt-vault/internal/config"
	"github.com/grigri201/prompt-vault/internal/container"
	"github.com/grigri201/prompt-vault/internal/gist"
	"github.com/grigri201/prompt-vault/internal/interfaces"
	"github.com/grigri201/prompt-vault/internal/paths"
	"github.com/grigri201/prompt-vault/internal/wire"
)

// Injectors from wire.go:

// buildContainer creates a new dependency container using wire
func buildContainer() *container.Container {
	pathManager := wire.ProvidePathManager()
	cacheManager := wire.ProvideCacheManager(pathManager)
	manager := wire.ProvideConfigManager(pathManager)
	authManager := wire.ProvideAuthManager(pathManager)
	client := wire.ProvideGistClient(manager)
	syncManager := wire.ProvideSyncManager(cacheManager, authManager, client)
	middleware := wire.ProvideSyncMiddleware(syncManager)
	containerContainer := provideContainer(pathManager, cacheManager, manager, authManager, client, syncManager, middleware)
	return containerContainer
}

// wire.go:

// provideContainer creates a Container with all dependencies
func provideContainer(
	pathManager *paths.PathManager,
	cacheManager interfaces.CacheManager,
	configManager *config.Manager,
	authManager interfaces.AuthManager,
	gistClient *gist.Client,
	syncManager interfaces.SyncManager,
	syncMiddleware interfaces.SyncMiddleware,
) *container.Container {
	return &container.Container{
		PathManager:    pathManager,
		CacheManager:   cacheManager,
		ConfigManager:  configManager,
		AuthManager:    authManager,
		GistClient:     gistClient,
		SyncManager:    syncManager,
		SyncMiddleware: syncMiddleware,
	}
}
